export const LOGIN_USER_START='LOGIN_USER_START'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'

export const FETCH_USER_START='FETCH_USER_START'
export const FETCH_USER_SUCCESS='FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL='FETCH_USER_FAIL'
